### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by frmdstryr** [bcdev/jpy#100]
Is there any benchmarks? Would be interesting to see how this compares to something like [pyjnius](https://github.com/kivy/pyjnius)?

**Comment by forman** [comment]
Not yet. Heard about pyjnius for the first time. I'd be happy (or not, hehe) to see some too but I don't have the time to do so. Let me know if you produce something!

**Comment by frmdstryr** [comment]
I actually implemented what I needed in another way. So I can close this. Thanks though!
