### ISSUE TITLE
Kernel restarts on jpy.get_type

### ISSUE THREAD

**Issue by homosepian** [bcdev/jpy#110]
jpy.create_jvm(['-Xmx512M', '-Djava.class.path=/path/to/my.jar'])
Main = jpy.get_type('pkg.Main')
MyClass = jpy.get_type('pkg.pkg2.MyClass')

The second call results in a kernel restart, notebook shows a message: "The kernel appears to have died. It will restart automatically".
The problem appears to be getting a class which is more than one package deep in the jar file.

Ubuntu 16.04, python 2.7

**Comment by forman** [comment]
Please explain "kernel" you referring to,  are you maybe using `jpy` in a Jupyter Notebook with a Python *kernel*? If so, it is still strange, as we use `jpy` with any package depth. See also all the unit tests that are green.

**Comment by homosepian** [comment]
I'm using ipython notebook, maybe something's wrong with my setup? I'm a Java developer, not very proficient with Python. My goal is for our data-scientists to be able to invoke my Java code from their Pandas. I can try with Jupyter, see if it solves the problem.

**Comment by homosepian** [comment]
Tried also with Jupyter notebook, same result. Is my setup wrong? I have python 2.7 as default in my system and I installed Anaconda for python 2.7. I run notebook from the commandline with `jupyter notebook`. The error in the console:
[I 14:35:46.280 NotebookApp] Saving file at /Untitled22.ipynb
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcec9f2f66e, pid=18741, tid=0x00007fcee4d39700
#
# JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x67266e]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /path/to/hs_err_pid18741.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[I 14:36:52.043 NotebookApp] KernelRestarter: restarting kernel (1/5)
kernel 03f92a7a-fe0f-479f-a141-d0fc35273b60 restarted
[I 14:37:46.278 NotebookApp] Saving file at /Untitled22.ipynb

**Comment by homosepian** [comment]
Trying to build jpy again with Oracle's JDK 8, getting:
```
NDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/main/c/jni/org_jpy_DL.o -L/usr/lib/jvm/jdk1.8.0_144/jre/lib/amd64/server -ljvm -ldl -o build/lib.linux-x86_64-2.7/jdl.so -Xlinker -rpath /usr/lib/jvm/jdk1.8.0_144/jre/lib/amd64/server
running maven
Executing Maven goal 'package'
Error: JAVA_HOME is not defined correctly.
  We cannot execute $JDK_HOME/bin/java
```
However:
```
nira@nira-getsocial:~/informiz/jpy$ echo $JAVA_HOME
/usr/lib/jvm/jdk1.8.0_144
me@mylaptop:~/informiz/jpy$ $JDK_HOME/bin/java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

Any idea?

**Comment by homosepian** [comment]
Built jpy with Oracle JDK 8 and compiled my jars with the same JDK. Using Jupyter notebook (installed with Anaconda for python 2.7) and python 2.7.
Still getting a kernel restart when I try to load some types, but I think it's because I'm using scala classes that probably depend on libraries which are not available the classpath. Specifically I was testing with [akka](https://mvnrepository.com/artifact/com.typesafe.akka/akka-actor_2.11/2.5.6). 
With pure java everything works fine.

```
import sys
sys.path.append('/path/to/lib.linux-x86_64-2.7')
import jpy
jpy.create_jvm(['-Xmx512M', '-Djava.class.path=/path/to/akka.jar'])
Actor = jpy.get_type('akka.actor.Actor')
<crash>
```

[hs_err_pid25592.log](https://github.com/bcdev/jpy/files/1394071/hs_err_pid25592.log)
