### ISSUE TITLE
No such file or directory: 'README.md' / 'README.rst'

### ISSUE THREAD

**Issue by gatterius** [bcdev/jpy#130]
Hello!
I'm trying to install JEP, but keep getting error by either installing from github repository:
Traceback (most recent call last):
  File "C:\jpy-master\setup.py", line 312, in <module>
    long_description=_read('README.md') + '\n\n' + _read('CHANGES.md'),
  File "C:\jpy-master\setup.py", line 189, in _read
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
(though the file README.md is in the folder)

or by installing using pip
Complete output from command python setup.py egg_info:
    Building a 64-bit library for a Windows system
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-i8r_cc43\jpy\setup.py", line 100, in <module>
        with open('README.rst') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

running on:
- Windows 10 x64:
- Python 3.6.5:
- JDK 9.0.4:

What can be done to successfully install jpy?

**Comment by forman** [comment]
Could you please describe how you try to install jpy step-by-step. Note, after checking out jpy from GitHub you need to make the checked-out directory your working directory.

**Comment by gatterius** [comment]
I've tried to reinstall C++, now instead of simple "no C++ installed" I get this long log of warnings and errors, resulting in installation failure.
[log.txt](https://github.com/bcdev/jpy/files/2010770/log.txt)

**Comment by gatterius** [comment]
Reinstallation of C++ with WIndows 10 and 8.1 SDKs has helped.
