### ISSUE TITLE
PyPI project iris: Does anyone here have access to the account that owns it? (Urgent)

### ISSUE THREAD

**Issue by jamadden** [bcdev/jpy#172]
Hi! I'm sorry for intruding with a message that's only tangentially related to this project, but I'm one of the moderators for pypi.org, the Python Package Index. In https://github.com/pypa/pypi-support/issues/180 someone has requested a transfer of https://pypi.org/project/iris/ to a different owner. PEP 541 requires attempting to get in touch with the current project owner before that can happen.

The email address listed for iris bounces. The [owner of the project](https://pypi.org/user/illumon/) also owns https://pypi.org/project/illumon-jpy/, which lists this repository as its homepage. I'm opening this issue in the hopes that someone here can help us get in touch with the owner and facilitate resolving the issue. If you are the owner or can contact them, the PyPI admins would appreciate it if you could respond to https://github.com/pypa/pypi-support/issues/180. (In https://github.com/bcdev/jpy/issues/11 it looks like @forman may have been involved.)

Thank you!

**Comment by devinrsmith** [comment]
Hi @jamadden,

Thanks again for reaching out. I've replied to https://github.com/pypa/pypi-support/issues/180 - https://github.com/bcdev/jpy is not the owner of https://pypi.org/project/iris/, so I think this ticket can be closed.

Thanks,
-Devin

**Comment by marpet** [comment]
Good that this could be clarified.
