### ISSUE TITLE
    c1: fatal error C1083: Cannot open source file: 'src\main\c\jpy_module.c': No such file or directory

### ISSUE THREAD

**Issue by MelpomeniZoka** [bcdev/jpy#193]
I faced several errors while trying to install the jpy package. Hope you can help me with these ones.
Thank you in advance. 

(base) C:\WINDOWS\system32>pip install -e git+https://github.com/bcdev/jpy#egg=jpy
Obtaining jpy from git+https://github.com/bcdev/jpy#egg=jpy
  Updating c:\windows\system32\src\jpy clone
Installing collected packages: jpy
  Running setup.py develop for jpy
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Meni D Luffy\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\WINDOWS\\system32\\src\\jpy\\setup.py'"'"'; __file__='"'"'C:\\WINDOWS\\system32\\src\\jpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\WINDOWS\system32\src\jpy\
    Complete output (15 lines):
    running develop
    running egg_info
    writing jpy.egg-info\PKG-INFO
    writing dependency_links to jpy.egg-info\dependency_links.txt
    writing top-level names to jpy.egg-info\top_level.txt
    reading manifest file 'jpy.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'lib\*.jar'
    writing manifest file 'jpy.egg-info\SOURCES.txt'
    running build_ext
    building 'jpy' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -Isrc\main\c "-IC:\Program Files\Java\jdk-16.0.1\include" "-IC:\Program Files\Java\jdk-16.0.1\include\win32" "-IC:\Users\Meni D Luffy\anaconda3\include" "-IC:\Users\Meni D Luffy\anaconda3\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc\main\c\jpy_module.c /Fobuild\temp.win-amd64-3.7\Release\src\main\c\jpy_module.obj
    jpy_module.c
    c1: fatal error C1083: Cannot open source file: 'src\main\c\jpy_module.c': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Meni D Luffy\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\WINDOWS\\system32\\src\\jpy\\setup.py'"'"'; __file__='"'"'C:\\WINDOWS\\system32\\src\\jpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by marpet** [comment]
You are running this command from C:\WINDOWS\system32, But I think the source code is not located there. Run the command from project location. Then it should work.

**Comment by MelpomeniZoka** [comment]
Thank you again Marco Peters. Just for your information, I tried to
imported it on Python but the following error occurred:

ImportError: DLL load failed: The specified module could not be found

To fix this error I entered the following two lines before importing the
package and it worked.

import jpyutil
jpyutil.init_jvm(jvm_maxmem='512M')import jpy

Have a nice day. :)

Στις Τετ, 21 Απρ 2021 στις 10:29 π.μ., ο/η Marco Peters <
***@***.***> έγραψε:
