### ISSUE TITLE
Provide compatibility with Python 3.2

### ISSUE THREAD

**Issue by forman** [bcdev/jpy#23]
For example, the 3.3 function PyUnicode_AsUTF8() can be replaced as follows:

       PyObject* pyUTF8 = PyUnicode_AsEncodedString(pyUnicode, "utf-8", "replace");
       char* chars = PyBytes_AsString(pyUTF8);
       ...
       Py_DECREF(pyUTF8);

**Comment by bcdev** [comment]
Won't fix.
