### ISSUE TITLE
array.fromstring('str', 'int')  and array.tostring()

### ISSUE THREAD

**Issue by zhihuiFan** [bcdev/jpy#44]
Hi forman:
  >>> b = jpy.array('int', [1,2,3])
 >>> b.toString()
 '[I@3f2a09d5'

 But what I want to do is if I got string  '[I@3f2a09d5', is it possible to get [1,2,3].   I have spent a lot of time on this,  appreciate for your help!

**Comment by forman** [comment]
b.toString() calls the `java.lang.Object.toString()` method on the b object which is a Java `int[]`. Unfortunately this will not return the textual representation of the array data, but of the reference to a Java `java.lang.String` object. This is not what you want.
Try the `java.util.Arrays.toString()` method: http://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#toString(int[]). 
Using jpy in Python:

```java
b = jpy.array('int', [1,2,3])
Arrays = jpy.get_type('java.util.Arrays')
Arrays.toString(b)
```

-- Norman

**Comment by zhihuiFan** [comment]
Thank you very much.  so I know that it is impossible.
