### ISSUE TITLE
How to remove a loaded module

### ISSUE THREAD

**Issue by krishna-k-1** [bcdev/jpy#49]
Hi,

I have loaded a script (module) into Python Interpreter using the below

PyModule.extendSysPath(Path_to_Script, true);
PyModule.importModule(Script_Name)

Now I have to remove this module.
How can I do this?
Is there any function in C-API?

Thanks a lot.

**Comment by forman** [comment]
Dear user,

Afaik and as you can see from the Python C-API documentation 
(https://docs.python.org/3/c-api/import.html), there is no way to unload 
modules. However there is a reload function (PyImport_ReloadModule) 
which seems to udate a module already loaded previously. If this helps, 
I could add a method to the jpy Java API, e.g. PyModule.reload().

Regards
     Norman



Am 18.06.2015 um 21:29 schrieb Krishna Rangaiah. K:
>
> Hi,
>
> I have loaded a script (module) into Python Interpreter using the below
>
> PyModule.extendSysPath(Path_to_Script, true);
> PyModule.importModule(Script_Name)
>
> Now I have to remove this module.
> How can I do this?
> Is there any function in C-API?
>
> Thanks a lot.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bcdev/jpy/issues/49>.
>

-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dipl. Ing. Norman Fomferra
Brockmann Consult GmbH
www.brockmann-consult.de
Max-Planck-Straße 2
D-21502 Geesthacht
Tel: +49 (0)4152 889 303
Fax: +49 (0)4152 889 333
Amtsgericht Geesthacht HRB 698
Geschäftsführer Dr. Carsten Brockmann
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Please help Brockmann Consult to respect the
environment by not printing this email.

**Comment by krishna-k-1** [comment]
HI Norman,

Thank you for your response.
Please provide that method.

Krishna.
