### ISSUE TITLE
Modifying an array wrapped by JArray

### ISSUE THREAD

**Issue by valgur** [bcdev/jpy#51]
JArray provides a convenient view to an array's elements but seems to hide access to any other methods, particularly to ones that modify its contents (remove(), clear(), add(), etc). Is there any way to access the Java object that is wrapped by a JArray directly?

Also, doing "del array[i]" to remove an element crashes the Python interpreter for me.

**Comment by forman** [comment]
Not sure what you mean. Which JArray are you referring to? Is it the Python type in jpy or do you you a another Java API named JArray from Python via jpy?
Primitive Java arrays don't have any methods but the ones they inhertit from java-lang.Object. Even from Java, you cannot modify array objects, you can only change their elements.
But: the Java arrays wrapped by jpy can be used wherever Python *buffers* or array-like objects are expected as argument. You can create numpy arrays with jpy arrays as initializer or create Python array objects. Usually, no extra memory will be used! See
* https://docs.python.org/2/library/array.html
* http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html

Anyway, I consider the "del array[i]" being a critical bug which is to be fixed soon.

**Comment by valgur** [comment]
Ah, on a second look, my question was pretty misguided.

My intention was to read SNAP graphs and modify them in-memory via snappy. Unfortunately, it seems that the DomElement, XppDomElement and XppDom classes used to represent the graph's parameters do not provide any methods to remove children elements from a DOM element. So I attempted to do that by modifying the XppDom's childList, that can be accessed by the XppDom[] getChildren() method, directly. What I missed, though, was that the List is converted to an XppDom[] array by the method. So that approach could not have worked anyway.

Sorry for the confusion and thanks a lot for the reply, still. The problem had nothing to do with jpy.
