### ISSUE TITLE
Loading of jpy DLL fails for user-specific Python installations on Windows

### ISSUE THREAD

**Issue by forman** [bcdev/jpy#58]
Just got the following error on Windows 10 with Visual Studio 14:

    Running org.jpy.PyLibTest
    org.jpy.PyLib: entered static initializer    
    org.jpy.PyLibConfig: entered static initializer
    org.jpy.PyLibConfig: loading configuration file build\lib.win-amd64-3.4\jpyconfig.properties
    org.jpy.PyLibConfig: exited static initializer
    org.jpy.PyLib: System.load("C:\Users\Norman\IdeaProjects\jpy\build\lib.win-amd64-3.4\jpy.pyd")
    Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
    org.jpy.PyLibTest  Time elapsed: 0.009 sec  <<< ERROR!
    java.lang.UnsatisfiedLinkError: C:\Users\Norman\IdeaProjects\jpy\build\lib.win-amd64-3.4\jpy.pyd: %1 ist keine zulõssige Win32-Anwendung
            at java.lang.ClassLoader$NativeLibrary.load(Native Method)
            at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
            at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
            at java.lang.Runtime.load0(Runtime.java:809)
            at java.lang.System.load(System.java:1086)
            at org.jpy.PyLib.loadLib(PyLib.java:356)
            at org.jpy.PyLib.<clinit>(PyLib.java:370)
            ...

The problem seems to occur only with Windows Python installations which have been installed with the option "Install Python just for me" (instead of "for all users"). In this case the python34.dll is placed in the Python installation directory rather than in C:\Windows\system32 (64-bit Python) or C:\Windows\SysWOW64 (32-bit Python).

**Comment by bcdev** [comment]
It is fixed now.
