### ISSUE TITLE
PIP install fails on master

### ISSUE THREAD

**Issue by francbartoli** [bcdev/jpy#65]
After cloning the repository locally the installation from there into a clean virtualenv fails with the error below:

*$ cd jpy
*$ pip install --no-cache-dir .*
....
*NameError: name 'build_dir' is not defined*

**Comment by forman** [comment]
The setup.py in jpy was designed to generate wheels for a specific Python version and an (Oracle) Java SDK. Set JAVA_HOME to your JDK home, before running setup.py.  To run all the tests, you also need Maven installed. On Windows you'll additionally need a Windows SDK or Visual Studio installation.
 
    $ export JAVA_HOME=<your JDK home path>
    $ cd jpy
    $ python setup.py --maven bdist_wheel

Then, find your wheel in the dist directory.

**Comment by francbartoli** [comment]
Still failing with JAVA_HOME set. IMHO the issue is not related to the JDK rather than to the temporary directory where the build is supposed to live.

It seems to be that the option --maven is not standard and used to force a build based only on Maven. Did you plan also to support a standard build?

**Comment by forman** [comment]
Yes, "--maven" is not standard. But as jpy is bi-directional, the build also includes Java compilation and testing. 

On which platform are you? Which Python?

**Comment by francbartoli** [comment]
Mac OSX 10.9.5 - x86_64
Python 2.7.10
