### ISSUE TITLE
Java double, python float

### ISSUE THREAD

**Issue by ecthx** [bcdev/jpy#69]
So my java app needs to pass a double  variable to python function.
When I do that I cant do any calculations on that variable because double type does
not exist in python. How should I take care of this? I would prefer not to convert everything to String

**Comment by Techcable** [comment]
A Python float is implemented as a java double.
The output of `sys.float_info.max` should be` 1.7976931348623157e+308` (just like a java double.)

**Comment by ecthx** [comment]
I understand what you are saying but my problem seems to be different.
When I pass my double variable from Java to python and then ask python to give me its type I get <type 'double'>. I don't understand why this happens. When I try to add my double variable from Java to python float I get an exception.  I did some tests and it seems that jpy handles it better when calling Java from python. 
![screenshot from 2016-06-13 20-39-41](https://cloud.githubusercontent.com/assets/16616179/16028731/cf0992ce-31a7-11e6-8168-5313d9542ff2.png)
