### ISSUE TITLE
Java call python failed because of not able to load dll that Python code is used

### ISSUE THREAD

**Issue by jh555** [bcdev/jpy#81]
I use java to call python method using Jpy. If python code is simple one without calling other dll. It works. However, when I have python call c dll function, I have some errors:

Type: <class 'OSError'>
 Value: cannot load library xxxxxxx.dll: error 0x7e****

How should I use Jpy to call the python method that use dll inside?

Here is method I use to call python function:
 PyModule plugInModule = PyModule.importModule(nameOfFile);
 PyObject result = plugInModule.callMethod(nameOfFunc);

Thanks,

**Comment by forman** [comment]
Which of the two lines cause the error?

    PyModule plugInModule = PyModule.importModule(nameOfFile);
    PyObject result = plugInModule.callMethod(nameOfFunc);

If `nameOfFile` is the name of a Python module which has some DLL dependency and `nameOfFunc` is a function exported by that Python module, then "normal" Python rules should apply for loading the DLL. It should have nothing to do with `jpy` - actually.

Try to find out where youre code expect the DLL to be, http://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency.

**Comment by jh555** [comment]
Thanks, callMethod is causing the error because one of function within that function calling other dll function. 
If I run this python script from command console, it works. Only when I try to use Jpy to run from Java, dll could not find.  But .dll exist in that directory.  
In python script, there is "from xxx.xx.xxx import xxx_xxx" in order to access dll functions. I am not sure if in java jpy interface, need to have similar call in order to enable dll calling.  
If you have some example to show how I could use Java to call python script that has some import dll, that will be very helpful.  I am struggling on how to use Jpy even I went through all source code, example or test.

**Comment by jh555** [comment]
I create a simple python file and java file.  I am trying to print out sys.argv in python, I called it from Java through jpy, it gives me error. 
Value: module 'sys' has no attribute 'argv'
Is Jpy not able to find sys python? 

Here is simple example. 
public class TestpyfromJava {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws IOException, InterruptedException {
        test();
    }

    public static void test() throws IOException {

        String value = getPythonVersion();
        String importPath = new File("src/testpyfromjava").getCanonicalPath();
        PyLib.startPython(importPath);

        // Import the Python module
        PyModule plugInModule = PyModule.importModule("copy_files");

         // call function directly
        PyObject result = plugInModule.call("display_usage");
        //String result = plugIn.display_usage();
        System.out.println(result.getStringValue());
        PyLib.stopPython();
    }

/////////////////////////////////// python  copy_files.py////////////////////////////////////
import sys
import os
import time
import getopt
import struct
import shutil
import glob
import errno

def display_usage():
    print(sys.argv)
    print("")
    print("copy_files.py options")
    print("")
    print("COMMAND OPTIONS")
    print("   --help                         Display this message")
    print("")
    print("FILE OPTIONS")
    print("   --file=FILE                    This file specifies the software folder root")
    print("                                  into which all the files will be copied")
    print("")
    print("TYPE")
    print("   --type=(200, 400, 800)         All the file and folder names are derived from the type")
    return "0"

def Main():
    display_usage()

if __name__ == "__main__":
    Main()

**Comment by jh555** [comment]
I have fixed issue with Dll.  The solution is add path to system environment.  Thanks.
However, if you could take a look why sys.argv does not work, that will be helpful.  sys.version is ok, but not sys.argv.

**Comment by voutilad** [comment]
Fascinating issue @jh555! I dug through the Python source code and found `sys.argv` is a special dynamic object since the `sys` module is implemented in C in CPython. It ends up reading values set by Python's `main.c` `Py_Main` function called when the Python executable is run.

Since JPY isn't running the Python executable itself, the value isn't set. Hence the error!

**Comment by forman** [comment]
@jh555 and @voutilad, thanks! PR accepted.
Hope to find some time soon to deploy a stable jpy version for PyPi and Conda.

**Comment by jh555** [comment]
What is the solution for sys.argv?  When I use Java to call Python file from other people, if it contains sys.argv, it will fail.  Is a new version released?

**Comment by voutilad** [comment]
@forman have you thought about integration with something like [Travis](https://travis-ci.org)? I'll open a PR if you're interested. I've just integrated my fork of jpy with Travis for automated builds (See https://travis-ci.org/voutilad/jpy/builds/204255868). In other projects I work on, we use Travis to automate publishing new tagged versions to PyPi so to release new versions it's just pushing a Git tag.

**Comment by voutilad** [comment]
@jh555 are you installing from PyPI or building locally? If you're building locally, issue a `git pull` to grab the latest from the master branch which contains the fix.

If you aren't building locally, you'll need to clone or download the latest copy of the master branch of the project and follow the build instructions in the [README.rst](https://github.com/bcdev/jpy/blob/master/README.rst) (Basically `python setup.py --maven bdist_wheel` but you need your environment configured properly.)

If you can build it locally without error, you can run `python setup.py install` to install a copy into your local Python site packages (or active[ virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/)).

**Comment by jh555** [comment]
I build locally.  I will try to pull and rebuild again. 
Thanks,

**Comment by voutilad** [comment]
@jh555 were you successful?

**Comment by jh555** [comment]
Yes.  It works.  Thanks,
