### ISSUE TITLE
Compiling in Java 8 - invalid ELF header (Possible cause: endianness mismatch)

### ISSUE THREAD

**Issue by madhawav** [bcdev/jpy#86]
Hi,
I am developing a Java Application with library jpy.jar.
I added the dependency through maven to jpy.jar and called PyLib.startPython(). Then, build process complained asking me to set system property jpy.jpyLib. Then, I added the location of jpy.jar (jpy-0.9-SNAPSHOT.jar) as system property jpy.jpyLib. Now, I get the following new error during maven build. 

**> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:java (default) on project org.example.learn2: An exception occured while executing the Java class. null: InvocationTargetException:** **~/jpy/lib/jpy-0.9-SNAPSHOT.jar:~/jpy/lib/jpy-0.9-SNAPSHOT.jar: invalid ELF header (Possible cause: endianness mismatch) -> [Help 1]**

Am I doing something wrong? How to fix this?

**Comment by voutilad** [comment]
What host OS are you running on? (For example, Windows 64-bit, macOS, Ubuntu 14.10 64-bit.) Only certain native libraries are built and distributed with JPY at the moment and I'm guessing it's trying to use the wrong one.

**Comment by forman** [comment]
@madhawav it is quite easy to build jpy for Unix/Darwin, please have a look into the README.

**Comment by madhawav** [comment]
Hi,
I managed to get this issue solved. 
The path to "jpy.cpython-35m-x86_64-linux-gnu.so" should be provided as system property "jpy.jpyLib" instead of the *.jar file I have provided previously.

Thanks
