### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: PyLib not initialized

### ISSUE THREAD

**Issue by i-akbari** [bcdev/jpy#88]
I installed jpy and add jpy-0.9-SNAPSHOT.jar file to libraries in Netbeans. I also add proper properties file to the project but When I run below code it gives me error. What is the problem?

Code:
```
package Main;
import org.jpy.*;
public class Main
{
    public static void main(String[] args)
    {
        PyModule sys = PyModule.importModule("sys");
    }
}
```

Error:
> Exception in thread "main" java.lang.RuntimeException: PyLib not initialized
> 	at org.jpy.PyLib.assertPythonRuns(PyLib.java:152)
> 	at org.jpy.PyModule.importModule(PyModule.java:91)
> 	at Main.Main.main(Main.java:11)
> /home/.../.cache/netbeans/8.1/executor-snippets/run.xml:53: Java returned: 1

**Comment by i-akbari** [comment]
The solution is quite simple! First of all we must run a python process.

```
package Main;
import org.jpy.*;

public class Main
{
    public static void main(String[] args)
    {
        PyLib.startPython();
        PyModule sys = PyModule.importModule("sys");
    }
}
```

The samples are useful.

**Comment by marpet** [comment]
Great!
