### ISSUE TITLE
Calling external DLL function and it gives error as AttributeError: 'function' object has no attribute '_jffi_type'

### ISSUE THREAD

**Issue by shahidlear** [bcdev/jpy#96]
Hi Friends,

I am using external DLL for NeoVI library and when DLL tx message function is called it gives errors as mentioned below
Exception in thread "MainThread" Traceback (most recent call last):
  File "src.py", line 46, in getEmployeeFirst
    res=dev.tx_raw_message(msg,1)
  File "C:\jython\Lib\site-packages\neovi\neodevice.py", line 153, in tx_raw_message
    return neovi.TxMessages(self.handle, msg, network_id)
  File "C:\jython\Lib\site-packages\neovi\neovi.py", line 486, in TxMessages
    apilib.icsneoTxMessages(hObject, msgs, network_id, num_msgs)
AttributeError: 'function' object has no attribute '_jffi_type'

if any one face same issue please provide me solution for same

**Comment by marpet** [comment]
I think this issue is not related to jpy.

**Comment by shahidlear** [comment]
This is related Jthyon

**Comment by marpet** [comment]
Then you are posting in the wrong project

**Comment by shahidlear** [comment]
OK..I though Jpy is same as jython

**Comment by shahidlear** [comment]
Jython is Java+Python
