### ISSUE TITLE
RuntimeError: jpy: No JVM available

### ISSUE THREAD

**Issue by XingweiLin** [bcdev/jpy#98]
Hi,
I'm in `ipython` environment.
I used this script:
```
import jpy
jpy.get_type()
```
It reported errors:
> RuntimeError: jpy: No JVM available

And I have set `LD_LIBRARY_PATH` in `~/.bashrc`:
`export LD_LIBRARY_PATH=/usr/local/java8/jdk1.8.0_77/jre/lib/amd64/server:$LD_LIBRARY_PATH`

So how to resolve this issue? I want to invoke Java method from python.

**Comment by voutilad** [comment]
Did you make a call to `jpy.create_jvm`? Make sure you call that function and pass in a list of any additional JVM arguments. (Currently it expects a non-`None` value, which is probably an issue worth fixing since it's not very intuitive.) Here's an example from my Python repl:

```
$ JAVA_HOME=/Library/Java/Home python
Python 3.6.1 (default, Mar 23 2017, 16:49:06)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpy
>>> jpy.create_jvm([])
>>> s = jpy.get_type('java.lang.String')
>>> print(s('hello jpy!'))
hello jpy!
>>> print(type(s('hi')))
<class 'java.lang.String'>
```

**Comment by XingweiLin** [comment]
@voutilad 
Thank you for your reply. 
It's because that I didn't call `jpy.create_jvm` first.
